[versions]
kotlin = "2.3.20-Beta2"
ksp = "2.3.4"
cmp = "1.10.0"
agp = "9.0.0"
androidx-activity = "1.12.3"

coroutines = "1.10.2"

material3 = "1.10.0-alpha05"
stability = "0.6.6"

ktor = "3.4.0"

logback = "1.5.27"
koog = "0.6.1"


# App Architecture
koin = "4.2.0-RC1"
decompose = "3.4.0"
flowmvi = "3.3.0-alpha03"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }

# Koin
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }

# Decompose
decompose-core = { module = "com.arkivanov.decompose:decompose", version.ref = "decompose" }
decompose-compose = { module = "com.arkivanov.decompose:extensions-compose", version.ref = "decompose" }

# FlowMVI
flowmvi-core = { module = "pro.respawn.flowmvi:core", version.ref = "flowmvi" }
flowmvi-essenty = { module = "pro.respawn.flowmvi:essenty", version.ref = "flowmvi" }
flowmvi-essenty-compose = { module = "pro.respawn.flowmvi:essenty-compose", version.ref = "flowmvi" }


kotlinx-coroutinesSwing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "coroutines" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }


compose-uiTooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "cmp" }
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "cmp" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "cmp" }
compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3" }
compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "cmp" }
compose-components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "cmp" }
compose-uiToolingPreview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "cmp" }


gradle-plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradle-plugin-android = { module = "com.android.tools.build:gradle", version.ref = "agp" }
gradle-plugin-compose = { module = "org.jetbrains.compose:org.jetbrains.compose.gradle.plugin", version.ref = "cmp" }
gradle-plugin-compose-compiler = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
gradle-plugin-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
gradle-plugin-ksp = { module = "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }

logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
ktor-serverCore = { module = "io.ktor:ktor-server-core-jvm", version.ref = "ktor" }
ktor-serverNetty = { module = "io.ktor:ktor-server-netty-jvm", version.ref = "ktor" }
ktor-serverTestHost = { module = "io.ktor:ktor-server-test-host-jvm", version.ref = "ktor" }

koog-ktor = { module = "ai.koog:koog-ktor", version.ref = "koog" }


[bundles]
presentation-api = ["decompose-core", "flowmvi-core", "flowmvi-essenty"]


[plugins]
androidApplication = { id = "com.android.application" }
androidLibrary = { id = "com.android.kotlin.multiplatform.library" }
composeMultiplatform = { id = "org.jetbrains.compose" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization" }
ksp = { id = "com.google.devtools.ksp" }

stability-analyzer = { id = "com.github.skydoves.compose.stability.analyzer", version.ref = "stability"}

kotlinJvm = { id = "org.jetbrains.kotlin.jvm" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }
